# Setup
title:               Mark's homepage
tagline:             'A Journey'
url:                 https://slliao.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://slliao,github.io
  email:             mark.slliao@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
excerpt_separator:  '<!-- more -->'

