# Setup
title:               Mark Liao
tagline:             'A Journey from Physics to Engineering'
description:         'A blog that records things I learn'
url:                 https://slliao.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Mark Liao
  url:               https://slliao,github.io
  email:             mark.slliao@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

